### ISSUE TITLE
Error messasge with little inforamtion

### ISSUE THREAD

**Issue by qige96** [aartikis/RTEC#11]
Hi,

After I successfully run the `toy` example and other examples, I decided to dive into RTEC by first creating my own example:

1. I copied the folder of `toy` to `toyb`
2. I copied the section of `toy` from `defaults.toml` and create a new section with minimal modification: only update the directory from "toy" to "toyb"
```toml
[toyb]
# RTEC execution parameters 
event_description = '../examples/toyb/resources/patterns/rules.prolog'
input_mode = "csv"
input_providers = ['../examples/toyb/dataset/csv/toy_data.csv']
results_directory = "../examples/toyb/results"
background_knowledge = ['../examples/toyb/dataset/auxiliary/toy_var_domain.prolog']
window_size = 10
step = 10
start_time = 0
end_time = 50
clock_tick = 1
goals = []
stream_rate = 1
# Compiler parameters
dependency_graph_flag = true
dependency_graph_directory = '../examples/toyb/resources/graphs'
include_input = false
```

After that I run 
```shell
./run_rtec.sh --app=toyb
```
but got the following error message
```
(base) ricky@ricky-PC:~/TREAT/RTEC/execution scripts
$./run_rtec.sh --app=toyb
Window size: 10
Step: 10
Start time: 0
End time: 50
Input mode: csv
Stream rate: 1
Event description file (precompiled): ../examples/toyb/resources/patterns/rules.prolog
Background knowledge: ../examples/toyb/dataset/auxiliary/toy_var_domain.prolog
Input stream providers: ../examples/toyb/dataset/csv/toy_data.csv
Results directory: ../examples/toyb/results
Predicates to run before invoking RTEC: 
Will a dependency graph be produced?: yes
Dependency graph directory: ../examples/toyb/resources/graphs
Will the dependency graph include input entities?: no
Executing: ./aux/compile.sh --event-description=../examples/toyb/resources/patterns/rules.prolog --dependency-graph --dependency-graph-directory=../examples/toyb/resources/graphs --no-events
Compiled event description: ../examples/toyb/resources/patterns/rules.prolog.
Dependency graph without input entities: ../examples/toyb/resources/graphs/dependency_graph.png.
Successful compilation! Compiled event description in: ../examples/toyb/resources/patterns/compiled_rules.prolog
ERROR: -g continuousQueries(toyb,[event_description_files=['../examples/toyb/dataset/auxiliary/toy_var_domain.prolog','../examples/toyb/resources/patterns/compiled_rules.prolog'],window_size=10,step=10,start_time=0,end_time=50,input_mode=csv,stream_rate=1,results_directory='../examples/toyb/results',input_providers=['../examples/toyb/dataset/csv/toy_data.csv']]),halt.: false                                                               
(base) ricky@ricky-PC:~/TREAT/RTEC/execution scripts
```

Does anyone have any idea what is going wrong?

---

OS: ubuntu 20.04
Python: 3.9.7
Prolog: SWI-Prolog (threaded, 64 bits, version 8.5.15-97-g5c7d1f835)

Any comments will be appreciated.
